// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWptDXjO2cpL23e6L6uCeOgqyzbakjOYc',
    appId: '1:224133854760:web:7ae098537e5b581ca6271d',
    messagingSenderId: '224133854760',
    projectId: 'fitnestx-b82bb',
    authDomain: 'fitnestx-b82bb.firebaseapp.com',
    storageBucket: 'fitnestx-b82bb.firebasestorage.app',
    measurementId: 'G-M527NZ02F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9eijGZxNrKECUcRoGlsNXKJNzy91xUUw',
    appId: '1:224133854760:android:39a2469fc59614fda6271d',
    messagingSenderId: '224133854760',
    projectId: 'fitnestx-b82bb',
    storageBucket: 'fitnestx-b82bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnG1iioAua0XCYE1nkQke9acmGMUBgchU',
    appId: '1:224133854760:ios:94ecd44bb33c9f08a6271d',
    messagingSenderId: '224133854760',
    projectId: 'fitnestx-b82bb',
    storageBucket: 'fitnestx-b82bb.firebasestorage.app',
    iosBundleId: 'dev.adk.fitnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnG1iioAua0XCYE1nkQke9acmGMUBgchU',
    appId: '1:224133854760:ios:94ecd44bb33c9f08a6271d',
    messagingSenderId: '224133854760',
    projectId: 'fitnestx-b82bb',
    storageBucket: 'fitnestx-b82bb.firebasestorage.app',
    iosBundleId: 'dev.adk.fitnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWptDXjO2cpL23e6L6uCeOgqyzbakjOYc',
    appId: '1:224133854760:web:c787698432160500a6271d',
    messagingSenderId: '224133854760',
    projectId: 'fitnestx-b82bb',
    authDomain: 'fitnestx-b82bb.firebaseapp.com',
    storageBucket: 'fitnestx-b82bb.firebasestorage.app',
    measurementId: 'G-C4NN0GLJS6',
  );

}